### ISSUE TITLE
Rotate issue

### ISSUE THREAD

**Issue by okydk** [ytiurin/scale-crop-rotate#1]
It seems like EXIF rotation codes 6 & 8 should be swapped?
Tested with [these images](https://github.com/ianare/exif-samples/tree/master/jpg/orientation).
Great work btw!

**Comment by ytiurin** [comment]
@okydk Hi, sorry for the late response!

According to this document http://sylvana.net/jpegcrop/exif_orientation.html
8 is equivalent to 90 degrees rotation
6 relates to 270 degrees
those values are hardcoded into the script like so
```
    '90deg'      : 8,
    '180deg'     : 3,
    '270deg'     : 6,
    'horizontal' : 2,
    'vertical'   : 4
```
Does that resolve your concern?
